name: CD
on:
  push: 
    branches: [master]

  workflow_dispatch:

env:
  SERVER_HOST: 92.63.64.241
  SERVER_USER: laborant
  SERVER_PATH: hw-back

jobs:
  build-account-api:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Restore
        working-directory: ./HW.Account.API
        run: dotnet restore "HW.Account.API.csproj"
        
      - name: Build
        working-directory: ./HW.Account.API
        run: dotnet build "HW.Account.API.csproj" -c Release

  build-backend-api:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Restore
        working-directory: ./HW.Backend.API
        run: dotnet restore "HW.Backend.API.csproj"
        
      - name: Build
        working-directory: ./HW.Backend.API
        run: dotnet build "HW.Backend.API.csproj" -c Release

  build-email-reciever-mvc:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Restore
        working-directory: ./HW.EmailReciever.MVC
        run: dotnet restore "HW.EmailReciever.MVC.csproj"
        
      - name: Build
        working-directory: ./HW.EmailReciever.MVC
        run: dotnet build "HW.EmailReciever.MVC.csproj" -c Release

  build-file-manager-api:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Restore
        working-directory: ./HW.FileManager.API
        run: dotnet restore "HW.FileManager.API.csproj"
        
      - name: Build
        working-directory: ./HW.FileManager.API
        run: dotnet build "HW.FileManager.API.csproj" -c Release

  build-notification-api:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Restore
        working-directory: ./HW.Notification.API
        run: dotnet restore "HW.Notification.API.csproj"
        
      - name: Build
        working-directory: ./HW.Notification.API
        run: dotnet build "HW.Notification.API.csproj" -c Release
        
  deploy:
    needs:
      - build-account-api
      - build-backend-api
      - build-email-reciever-mvc
      - build-file-manager-api
      - build-notification-api
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        
      - name: Using a trusted host
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.KEY }}
          ssh-host: ${{env.SERVER_HOST}}

      - name: Upgrade docker-compose
        run: pip install docker-compose
        
      - run: touch .env

      - name: Create docker contaxt
        run: docker context create remote --docker "host=ssh://"${{env.SERVER_USER}}@${{env.SERVER_HOST}}

      - run:  docker context use remote

      - run: docker-compose --context remote down
      
      - name: docker-compose run
        run: docker-compose --context remote up -d --force-recreate
          
